font = ''

[text]
# define the text displayed in the application.
# escape sequences:
# \t: song title
# \a: album name
# \A: artist name
# \s1.0;: set the scale (to the default: 1.0)
# \h1.0;: set the height-alignment (to the default: 1.0 / align text to be on one baseline)
# \cRRGGBB: set color to this hex value.
# \cFFFFFF: default color (white)
# \iCover:<id>;: show cover with this ID (ID >= 0)
#    \iCover:0;
# \iCustomFile:<path>:: show cover stored in custom files at the given path (path terminated by #, is another textcfg)
#    \iCustomFile:my_image.jpg#
# \<char>: <char> (\\ => \, \# => #, \% => %, ...)
# custom properties:
# %<mode><search text>%
# %_word% returns the first property that includes "word"
# %>Year=% returns the end of the first property that starts with "Year=",
#          so if a song has "Year=2019", this would return "2019".
# %=Value% returns something if a property "Value" is found.
# IF:
# ?<condition>#<then>#<else>#
# If <condition> is not empty, the entire block will be replaced by the value generated by <then>.
# If <condition> is empty, the entire block will be replaced by the value generated by <else>.
# Examples:
# ?\A#by \A##
# If we know the artist's name, write "by " followed by the name,
# if not, don't write anything (## -> <else> is empty)
# ?\t#\t#(no title found)#
# If we know the title, write it. If not, write "(no title found)" instead.

status_bar = '''\t
\s0.5;?\A#\c505050by \c593D6E\A##?\a#?\A# ##\c505050on \c264524\a##\c808080?%>Year=%# (%>Year=%)## | \d'''

# Two lines
# 1:
# - Title (Size 1.0, White)
# - Duration (and, if set, Genre) in brackets (Size 0.5, Gray)
# - (\h0.5; = set height-align to 0.5, only affects flag image in second line)
# 2:
# - if there is an Artist:
#   - "by <Artist>" (purple)
#   - if there is a "Flag: <name>" tag, show the image saved as "<name>.png"
# - "on <Album>", if there is an Album (green)
# - "(<year>)", if there is a Year=<year> tag (gray)
idle_top = '''\t \s0.5;\c505050(\d?%>Genre=%#, %>Genre=%##)\h0.5;
?\A#\c505050by \c593D6E\A?%>Flag: %# \s0.25;\iCustomFile:%>Flag: %.png#\s0.5;####?\a#?\A# ##\c505050on \c264524\a##\c808080?%>Year=%# (%>Year=%)##'''

idle_side1 = ''
idle_side2 = ''
