[package]
name = "musicdb-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
directories = "5.0.1"
musicdb-lib = { version = "0.1.0", path = "../musicdb-lib" }
regex = "1.9.3"
speedy2d = { version = "1.12.0", optional = true }
toml = "0.7.6"
# mers_lib = { path = "../../mers/mers_lib", optional = true }

[features]
default = ["speedy2d"]
playback = ["musicdb-lib/playback"]
# merscfg = ["mers_lib"]
