[package]
name = "musicdb-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
awedio = "0.2.0"
base64 = "0.21.2"
rc-u8-reader = "2.0.16"
tokio = "1.29.1"
