# # compile for aarch64 linux
[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install --force musl-dev libasound2-dev"
]
default-target = "x86_64-unknown-linux-musl"

# compile for aarch64 android
# [build]
# pre-build = [
#     "dpkg --add-architecture $CROSS_DEB_ARCH",
#     "dpkg --add-architecture i386",
#     "apt-get update",
#     "apt-get install --assume-yes libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386",
# ]
# default-target = "aarch64-linux-android"
